#ifndef PUBLICSTRUCT_H
#define PUBLICSTRUCT_H
#include <QObject>

struct AgreementZXJC    //模拟南阳协议对应中芯京城
{
    QString RND_0 = "RND";
    QString EquipmentConnect_1 = "1";
    QString HostConnect_2 = "1";
    QString CH1ReceipeStart_3 = "N";
    QString N_4 = "N";
    QString CH3ReceipeStart_5 = "N";
    QString N_6 = "N";
    QString CH4ReceipeStart_7 = "N";
    QString N_8 = "N";
    QString CH6ReceipeStart_9 = "N";
    QString N_10 = "N";
    QString N_11 = "N";
    QString N_12 = "N";
    QString N_13 = "N";
    QString N_14 = "N";
    QString N_15 = "N";
    QString N_16 = "N";
    QString N_17 = "N";
    QString N_18 = "N";
    QString N_19 = "N";
    QString N_20 = "N";
    QString N_21 = "N";
    QString N_22 = "N";
    QString N_23 = "N";
    QString N_24 = "N";
    QString N_25 = "N";
    QString N_26 = "N";
    QString N_27 = "N";
    QString N_28 = "N";
    QString N_29 = "N";
    QString N_30 = "N";
    QString N_31 = "N";
    QString N_32 = "N";
    QString N_33 = "N";
    QString N_34 = "N";
    QString N_35 = "N";
    QString N_36 = "N";
    QString N_37 = "N";
    QString N_38 = "N";
    QString N_39 = "N";
    QString N_40 = "N";
    QString N_41 = "N";
    QString N_42 = "N";
    QString N_43 = "N";
    QString N_44 = "N";
    QString N_45 = "N";
    QString N_46 = "N";
    QString N_47 = "N";
    QString N_48 = "N";
    QString N_49 = "N";
    QString N_50 = "N";
    QString N_51 = "N";
    QString N_52 = "N";
    QString N_53 = "N";
    QString N_54 = "N";
    QString N_55 = "N";
    QString N_56 = "N";
    QString N_57 = "N";
    QString N_58 = "N";
    QString N_59 = "N";
    QString N_60 = "N";
    QString N_61 = "N";
    QString N_62 = "N";
    QString N_63 = "N";
    QString N_64 = "N";
    QString N_65 = "N";
    QString N_66 = "N";
    QString N_67 = "N";
    QString N_68 = "N";
    QString N_69 = "N";
    QString N_70 = "N";
    QString N_71 = "N";
    QString N_72 = "N";
    QString N_73 = "N";
    QString N_74 = "N";
    QString N_75 = "N";
    QString N_76 = "N";
    QString N_77 = "N";
    QString N_78 = "N";
    QString N_79 = "N";
    QString N_80 = "N";
    QString N_81 = "N";
    QString N_82 = "N";
    QString N_83 = "N";
    QString N_84 = "N";
    QString N_85 = "N";
    QString N_86 = "N";
    QString N_87 = "N";
    QString N_88 = "N";
    QString N_89 = "N";
    QString N_90 = "N";
    QString N_91 = "N";
    QString N_92 = "N";
    QString N_93 = "N";
    QString N_94 = "N";
    QString N_95 = "N";
    QString N_96 = "N";
    QString N_97 = "N";
    QString N_98 = "N";
    QString N_99 = "N";
    QString N_100 = "N";
    QString N_101 = "N";
    QString N_102 = "N";
    QString N_103 = "N";
    QString N_104 = "N";
    QString N_105 = "N";
    QString N_106 = "N";
    QString N_107 = "N";
    QString N_108 = "N";
    QString N_109 = "N";
    QString Ch1WaferID_110 = "N";
    QString Ch3WaferID_111 = "N";
    QString Ch4WaferID_112 = "N";
    QString Ch6WaferID_113 = "N";
    QString LLAWaferID_114 = "N";
    QString LLAWaferID_115 = "N";
    QString N_116 = "N";
    QString N_117 = "N";
    QString N_118 = "N";
    QString N_119 = "N";
    QString SecsHost_120 = "1";
    QString Equipment_121 = "1";
    QString Ch1Slot_122 = "N";
    QString Ch3Slot_123 = "N";
    QString Ch4Slot_124 = "N";
    QString Ch6Slot_125 = "N";
    QString LLASlot_126 = "N";
    QString LLBSlot_127 = "N";

    QString Splicing()  //拼接在一起
    {
        QString result = RND_0 + "," +
                EquipmentConnect_1 + "," +
                HostConnect_2 + "," +
                CH1ReceipeStart_3 + "," +
                N_4 + "," +
                CH3ReceipeStart_5 + "," +
                N_6 + "," +
                CH4ReceipeStart_7 + "," +
                N_8 + "," +
                CH6ReceipeStart_9 + "," +
                N_10 + "," +
                N_11 + "," +
                N_12 + "," +
                N_13 + "," +
                N_14 + "," +
                N_15 + "," +
                N_16 + "," +
                N_17 + "," +
                N_18 + "," +
                N_19 + "," +
                N_20 + "," +
                N_21 + "," +
                N_22 + "," +
                N_23 + "," +
                N_24 + "," +
                N_25 + "," +
                N_26 + "," +
                N_27 + "," +
                N_28 + "," +
                N_29 + "," +
                N_30 + "," +
                N_31 + "," +
                N_32 + "," +
                N_33 + "," +
                N_34 + "," +
                N_35 + "," +
                N_36 + "," +
                N_37 + "," +
                N_38 + "," +
                N_39 + "," +
                N_40 + "," +
                N_41 + "," +
                N_42 + "," +
                N_43 + "," +
                N_44 + "," +
                N_45 + "," +
                N_46 + "," +
                N_47 + "," +
                N_48 + "," +
                N_49 + "," +
                N_50 + "," +
                N_51 + "," +
                N_52 + "," +
                N_53 + "," +
                N_54 + "," +
                N_55 + "," +
                N_56 + "," +
                N_57 + "," +
                N_58 + "," +
                N_59 + "," +
                N_60 + "," +
                N_61 + "," +
                N_62 + "," +
                N_63 + "," +
                N_64 + "," +
                N_65 + "," +
                N_66 + "," +
                N_67 + "," +
                N_68 + "," +
                N_69 + "," +
                N_70 + "," +
                N_71 + "," +
                N_72 + "," +
                N_73 + "," +
                N_74 + "," +
                N_75 + "," +
                N_76 + "," +
                N_77 + "," +
                N_78 + "," +
                N_79 + "," +
                N_80 + "," +
                N_81 + "," +
                N_82 + "," +
                N_83 + "," +
                N_84 + "," +
                N_85 + "," +
                N_86 + "," +
                N_87 + "," +
                N_88 + "," +
                N_89 + "," +
                N_90 + "," +
                N_91 + "," +
                N_92 + "," +
                N_93 + "," +
                N_94 + "," +
                N_95 + "," +
                N_96 + "," +
                N_97 + "," +
                N_98 + "," +
                N_99 + "," +
                N_100 + "," +
                N_101 + "," +
                N_102 + "," +
                N_103 + "," +
                N_104 + "," +
                N_105 + "," +
                N_106 + "," +
                N_107 + "," +
                N_108 + "," +
                N_109 + "," +
                Ch1WaferID_110 + "," +
                Ch3WaferID_111 + "," +
                Ch4WaferID_112 + "," +
                Ch6WaferID_113 + "," +
                LLAWaferID_114 + "," +
                LLAWaferID_115 + "," +
                N_116 + "," +
                N_117 + "," +
                N_118 + "," +
                N_119 + "," +
                SecsHost_120 + "," +
                Equipment_121 + "," +
                Ch1Slot_122 + "," +
                Ch3Slot_123 + "," +
                Ch4Slot_124 + "," +
                Ch6Slot_125 + "," +
                LLASlot_126 + "," +
                LLBSlot_127;
        return result;
    }
};

#endif // PUBLICSTRUCT_H
